# 工作流程的名字
# https://github.com/subosito/flutter-action
name: build Openwrt Ipk
on:
  workflow_dispatch:
    inputs:
      version:
        description: "ipk version"
        required: true
        default: "0.0.1"
      target:
        description: 'build target ["arm64", "x64", "mipsel"]'
        required: true
        default: "x64"
env:
  TZ: Asia/Shanghai
  IPK_NAME: luci-app-mfun

permissions:
  contents: write
# 这个工作流程需要执行的任务
jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Detect build target
        id: set-matrix
        env:
          MATRIX_TARGET: ${{ github.event.inputs.target }}
        run: |
          if [ "x${MATRIX_TARGET}" = "x" -o "x${MATRIX_TARGET}" = "xall" ]; then \
            echo "matrix={\"target\":[\"arm64\", \"x64\", \"mipsel\"]}" >> $GITHUB_OUTPUT; \
          else \
            targets=""; \
            for target in ${MATRIX_TARGET}; do \
              targets="$targets, \"$target\"";
            done; \
            echo "matrix={\"target\":[${targets#, }]}" >> $GITHUB_OUTPUT; \
          fi
  build:
    needs: matrix
    runs-on: ubuntu-latest
    name: Build IPKs for ${{ matrix.target }}
    strategy:
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}
    steps:
      # 拉取项目代码
      - name: Checkout the code
        uses: actions/checkout@v3

      # 写入版本号
      - run: |
          sed -i  's/PKG_VERSION:=\(.*\)/PKG_VERSION:=${{ inputs.version }}/g' ${IPK_NAME}/Makefile

      - name: Import Env
        env:
          MATRIX_TARGET: ${{ matrix.target }}
        run: cat .github/workflows/${MATRIX_TARGET}.env >> "$GITHUB_ENV"

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo swapoff -a || true
          sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf rsync
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          # curl -fsSL https://raw.githubusercontent.com/P3TERX/dotfiles/master/.bashrc >> ~/.bashrc

      - name: Download SDK
        run: wget ${SDK_URL}${SDK_NAME}.tar.xz

      - name: Unpack SDK
        run: |
          mkdir ~/openwrt-sdk
          tar -xJf `pwd`/${SDK_NAME}.tar.xz --strip-components=1 -C ~/openwrt-sdk
          ln -s ${HOME}/openwrt-sdk ${SDK_NAME}

      - name: Clean Code
        run: |
          rm -f ${SDK_NAME}/package/linux/modules/*
          rm -f ${SDK_NAME}/package/kernel/linux/modules/*
          grep -lFr '$(call KernelPackage,' ${SDK_NAME}/package/linux | xargs -rn1 sed -i 's/ FILES:=/ XFILES:=/g' || true
          grep -lFr '$(call KernelPackage,' ${SDK_NAME}/package/kernel | xargs -rn1 sed -i 's/ FILES:=/ XFILES:=/g' || true
          find ${SDK_NAME}/target/linux -name 'modules.mk' | xargs -rn1 sed -i 's/ FILES:=/ XFILES:=/g' || true
          grep 'src-git base ' ${SDK_NAME}/feeds.conf.default > ${SDK_NAME}/feeds.conf
          grep 'src-git luci ' ${SDK_NAME}/feeds.conf.default >> ${SDK_NAME}/feeds.conf

      - name: Write Config
        run: |
          cat <<EOF >${SDK_NAME}/.config
          # CONFIG_SIGNED_PACKAGES is not set
          CONFIG_LUCI_LANG_zh_Hans=y
          CONFIG_LUCI_LANG_zh-cn=y
          EOF

      - name: Defconfig
        id: defconfig
        run: |
          cd ~/openwrt-sdk
          make defconfig
          sed -i 's/^CONFIG_PACKAGE_\(.*\)=m$/# CONFIG_PACKAGE_\1 is not set/' .config
          grep '^CONFIG_PACKAGE_' .config
          echo "status=success" >> $GITHUB_OUTPUT

      - name: "Install"
        run: |
          cd ~/openwrt-sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy Package
        run: |
          cp -r ./${IPK_NAME}/ ~/openwrt-sdk/package

      - name: Build IPK
        run: |
          cd ~/openwrt-sdk
          chmod 755 -R ./package/${IPK_NAME}
          make -j16 V=s package/${IPK_NAME}/compile

      # 提交下载
      - name: Upload bin directory
        uses: actions/upload-artifact@main
        with:
          name: ${{ env.SDK_ARCH }}
          path: ${{ env.SDK_NAME }}/bin/packages/${{ env.SDK_ARCH }}
